export const ADD_CAR_RECORD = 'ADD_CAR_RECORD';
export const GENERATE_OR_UPDATE_SCHEDULE = 'GENERATE_OR_UPDATE_SCHEDULE';
export const REPLACE_RECORD_FROM_ACTIVE_TO_PASSED = 'REPLACE_RECORD_FROM_ACTIVE_TO_PASSED';