export const ADD_CAR_RECORD = 'ADD_CAR_RECORD';
export const GENERATE_OR_UPDATE_DAYS = 'GENERATE_OR_UPDATE_DAYS';
export const REPLACE_RECORD_FROM_ACTIVE_TO_PASSED = 'REPLACE_RECORD_FROM_ACTIVE_TO_PASSED';